// Task templates organized by project
// Variable completion rates across projects
export const SEED_TASKS = {
  "user-authentication": [
    // To-do tasks (25% - 11 tasks)
    {
      title: "Implement password reset flow",
      status: "to-do",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 5,
      labels: ["feature"],
    },
    {
      title: "Add two-factor authentication",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 20,
      labels: ["feature", "enhancement"],
    },
    {
      title: "Fix session timeout handling",
      status: "to-do",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 3,
      labels: ["bug"],
    },
    {
      title: "Implement OAuth providers",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 25,
      labels: ["feature", "api"],
    },
    {
      title: "Add account lockout mechanism",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 12,
      labels: ["enhancement"],
    },
    {
      title: "Create password strength validator",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 8,
      labels: ["enhancement"],
    },
    {
      title: "Implement remember me functionality",
      status: "to-do",
      priority: "low",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Add biometric authentication",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 30,
      labels: ["feature"],
    },
    {
      title: "Fix token refresh logic",
      status: "to-do",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 4,
      labels: ["bug"],
    },
    {
      title: "Create login audit logs",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 15,
      labels: ["enhancement"],
    },
    {
      title: "Update authentication documentation",
      status: "to-do",
      priority: "low",
      hasDueDate: false,
      labels: ["documentation"],
    },

    // In-progress tasks (40% - 18 tasks)
    {
      title: "Implement JWT token system",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 7,
      labels: ["feature", "api"],
    },
    {
      title: "Add social login integration",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 14,
      labels: ["feature", "api"],
    },
    {
      title: "Create user registration flow",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 6,
      labels: ["feature"],
    },
    {
      title: "Implement email verification",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 10,
      labels: ["feature"],
    },
    {
      title: "Add role-based access control",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 9,
      labels: ["feature"],
    },
    {
      title: "Fix CSRF protection",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 5,
      labels: ["bug"],
    },
    {
      title: "Create password change API",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 11,
      labels: ["api"],
    },
    {
      title: "Implement session management",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 8,
      labels: ["feature"],
    },
    {
      title: "Add account deletion flow",
      status: "in-progress",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 18,
      labels: ["feature"],
    },
    {
      title: "Create login rate limiting",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 12,
      labels: ["enhancement"],
    },
    {
      title: "Implement magic link authentication",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 13,
      labels: ["feature"],
    },
    {
      title: "Add user profile management",
      status: "in-progress",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 20,
      labels: ["feature"],
    },
    {
      title: "Fix authentication error messages",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 6,
      labels: ["bug"],
    },
    {
      title: "Create authentication middleware",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 7,
      labels: ["api"],
    },
    {
      title: "Implement password hashing",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 4,
      labels: ["enhancement"],
    },
    {
      title: "Add login attempt tracking",
      status: "in-progress",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 16,
      labels: ["enhancement"],
    },
    {
      title: "Create authentication tests",
      status: "in-progress",
      priority: "medium",
      hasDueDate: false,
      labels: ["testing"],
    },
    {
      title: "Implement refresh token rotation",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 10,
      labels: ["enhancement"],
    },

    // Done tasks (35% - 16 tasks)
    {
      title: "Set up authentication infrastructure",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Create user login endpoint",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["api"],
    },
    {
      title: "Implement basic password authentication",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Add user logout functionality",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Create user model and schema",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Implement password encryption",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["enhancement"],
    },
    {
      title: "Add authentication error handling",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["enhancement"],
    },
    {
      title: "Create authentication service layer",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Implement user registration API",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["api"],
    },
    {
      title: "Add input validation for auth forms",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["enhancement"],
    },
    {
      title: "Create authentication UI components",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["design"],
    },
    {
      title: "Implement basic session storage",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Add authentication logging",
      status: "done",
      priority: "low",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Create user authentication tests",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["testing"],
    },
    {
      title: "Implement basic authorization checks",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Add authentication documentation",
      status: "done",
      priority: "low",
      hasDueDate: false,
      labels: ["documentation"],
    },
  ],

  "dashboard-analytics": [
    // To-do tasks (50% - 20 tasks)
    {
      title: "Implement real-time data streaming",
      status: "to-do",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 25,
      labels: ["feature", "api"],
    },
    {
      title: "Add custom date range selector",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 15,
      labels: ["feature", "design"],
    },
    {
      title: "Create export functionality",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 30,
      labels: ["feature"],
    },
    {
      title: "Implement data aggregation pipeline",
      status: "to-do",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 20,
      labels: ["feature"],
    },
    {
      title: "Add comparison view mode",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 18,
      labels: ["feature"],
    },
    {
      title: "Create performance metrics dashboard",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 22,
      labels: ["feature", "design"],
    },
    {
      title: "Implement data caching layer",
      status: "to-do",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 12,
      labels: ["enhancement"],
    },
    {
      title: "Add drill-down functionality",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 28,
      labels: ["feature"],
    },
    {
      title: "Create user behavior analytics",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 24,
      labels: ["feature"],
    },
    {
      title: "Implement alert system",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 16,
      labels: ["feature"],
    },
    {
      title: "Add data visualization library",
      status: "to-do",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 10,
      labels: ["enhancement"],
    },
    {
      title: "Create analytics API endpoints",
      status: "to-do",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 14,
      labels: ["api"],
    },
    {
      title: "Implement data filtering",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 11,
      labels: ["feature"],
    },
    {
      title: "Add chart customization options",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 26,
      labels: ["enhancement", "design"],
    },
    {
      title: "Create analytics documentation",
      status: "to-do",
      priority: "low",
      hasDueDate: false,
      labels: ["documentation"],
    },
    {
      title: "Implement data refresh mechanism",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 13,
      labels: ["enhancement"],
    },
    {
      title: "Add timezone support",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 19,
      labels: ["enhancement"],
    },
    {
      title: "Create analytics dashboard layout",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 17,
      labels: ["design"],
    },
    {
      title: "Implement data sampling",
      status: "to-do",
      priority: "low",
      hasDueDate: false,
      labels: ["enhancement"],
    },
    {
      title: "Add analytics unit tests",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 21,
      labels: ["testing"],
    },

    // In-progress tasks (35% - 14 tasks)
    {
      title: "Build chart components",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 9,
      labels: ["design"],
    },
    {
      title: "Implement data collection service",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 8,
      labels: ["feature"],
    },
    {
      title: "Create analytics data models",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 7,
      labels: [],
    },
    {
      title: "Add basic metrics calculation",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 6,
      labels: ["feature"],
    },
    {
      title: "Implement dashboard grid layout",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 12,
      labels: ["design"],
    },
    {
      title: "Create analytics service API",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 10,
      labels: ["api"],
    },
    {
      title: "Add data processing pipeline",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 11,
      labels: ["feature"],
    },
    {
      title: "Implement basic charts",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 8,
      labels: ["design"],
    },
    {
      title: "Create analytics database schema",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 5,
      labels: [],
    },
    {
      title: "Add data query optimization",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 13,
      labels: ["enhancement"],
    },
    {
      title: "Implement dashboard widgets",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 14,
      labels: ["design"],
    },
    {
      title: "Create analytics data pipeline",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 9,
      labels: ["feature"],
    },
    {
      title: "Add error handling for data queries",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 7,
      labels: ["enhancement"],
    },
    {
      title: "Implement loading states",
      status: "in-progress",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 6,
      labels: ["enhancement", "design"],
    },

    // Done tasks (15% - 6 tasks)
    {
      title: "Set up analytics infrastructure",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Create basic dashboard layout",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["design"],
    },
    {
      title: "Implement data collection basics",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Add basic analytics API",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["api"],
    },
    {
      title: "Create analytics database tables",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Implement basic data visualization",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["design"],
    },
  ],

  "notification-system": [
    // To-do tasks (35% - 18 tasks)
    {
      title: "Implement push notification service",
      status: "to-do",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 20,
      labels: ["feature"],
    },
    {
      title: "Add notification preferences UI",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 15,
      labels: ["feature", "design"],
    },
    {
      title: "Create notification templates",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 12,
      labels: ["feature"],
    },
    {
      title: "Implement notification scheduling",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 25,
      labels: ["feature"],
    },
    {
      title: "Add notification batching",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 22,
      labels: ["enhancement"],
    },
    {
      title: "Create notification analytics",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 28,
      labels: ["feature"],
    },
    {
      title: "Implement notification A/B testing",
      status: "to-do",
      priority: "low",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Add notification delivery tracking",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 18,
      labels: ["enhancement"],
    },
    {
      title: "Create notification center UI",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 16,
      labels: ["feature", "design"],
    },
    {
      title: "Implement notification filtering",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 14,
      labels: ["enhancement"],
    },
    {
      title: "Add notification sound settings",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 19,
      labels: ["feature"],
    },
    {
      title: "Create notification API documentation",
      status: "to-do",
      priority: "low",
      hasDueDate: false,
      labels: ["documentation"],
    },
    {
      title: "Implement notification queuing system",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 17,
      labels: ["enhancement"],
    },
    {
      title: "Add notification retry mechanism",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 13,
      labels: ["enhancement"],
    },
    {
      title: "Create notification testing framework",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 21,
      labels: ["testing"],
    },
    {
      title: "Implement notification rate limiting",
      status: "to-do",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 11,
      labels: ["enhancement"],
    },
    {
      title: "Add notification localization",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 24,
      labels: ["feature"],
    },
    {
      title: "Create notification admin panel",
      status: "to-do",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 26,
      labels: ["feature", "design"],
    },

    // In-progress tasks (40% - 20 tasks)
    {
      title: "Build email notification service",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 10,
      labels: ["feature"],
    },
    {
      title: "Implement in-app notifications",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 8,
      labels: ["feature"],
    },
    {
      title: "Create notification database schema",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 6,
      labels: [],
    },
    {
      title: "Add notification delivery service",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 9,
      labels: ["feature"],
    },
    {
      title: "Implement notification types system",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 11,
      labels: ["feature"],
    },
    {
      title: "Create notification UI components",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 12,
      labels: ["design"],
    },
    {
      title: "Add notification read/unread status",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 7,
      labels: ["feature"],
    },
    {
      title: "Implement notification API endpoints",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 8,
      labels: ["api"],
    },
    {
      title: "Create notification service layer",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 7,
      labels: [],
    },
    {
      title: "Add notification event handlers",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 10,
      labels: ["feature"],
    },
    {
      title: "Implement notification badge system",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 9,
      labels: ["feature", "design"],
    },
    {
      title: "Create notification storage system",
      status: "in-progress",
      priority: "high",
      hasDueDate: true,
      daysFromNow: 6,
      labels: [],
    },
    {
      title: "Add notification mark as read",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 5,
      labels: ["feature"],
    },
    {
      title: "Implement notification permissions",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 13,
      labels: ["feature"],
    },
    {
      title: "Create notification webhook system",
      status: "in-progress",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 14,
      labels: ["api"],
    },
    {
      title: "Add notification error handling",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 8,
      labels: ["enhancement"],
    },
    {
      title: "Implement notification aggregation",
      status: "in-progress",
      priority: "low",
      hasDueDate: true,
      daysFromNow: 15,
      labels: ["enhancement"],
    },
    {
      title: "Create notification background jobs",
      status: "in-progress",
      priority: "medium",
      hasDueDate: true,
      daysFromNow: 12,
      labels: ["feature"],
    },
    {
      title: "Add notification logging",
      status: "in-progress",
      priority: "low",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Implement notification testing",
      status: "in-progress",
      priority: "low",
      hasDueDate: false,
      labels: ["testing"],
    },

    // Done tasks (25% - 12 tasks)
    {
      title: "Set up notification infrastructure",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Create notification data models",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Implement basic notification API",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["api"],
    },
    {
      title: "Add notification creation service",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Create notification database tables",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Implement notification retrieval",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Add basic notification UI",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["design"],
    },
    {
      title: "Create notification service foundation",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Implement notification sending",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Add notification error handling",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["enhancement"],
    },
    {
      title: "Create notification tests",
      status: "done",
      priority: "low",
      hasDueDate: false,
      labels: ["testing"],
    },
    {
      title: "Implement basic notification types",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["feature"],
    },
  ],
};

// Completed projects - all tasks are done
export const SEED_COMPLETED_TASKS = {
  "onboarding-flow": [
    {
      title: "Design onboarding user flow",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["design"],
    },
    {
      title: "Create welcome screen",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["design", "feature"],
    },
    {
      title: "Implement step-by-step tutorial",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Add progress indicator",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["design"],
    },
    {
      title: "Create skip functionality",
      status: "done",
      priority: "low",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Implement onboarding analytics",
      status: "done",
      priority: "low",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Add interactive tooltips",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["design", "feature"],
    },
    {
      title: "Create onboarding completion screen",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["design"],
    },
    {
      title: "Implement onboarding persistence",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Add onboarding tests",
      status: "done",
      priority: "low",
      hasDueDate: false,
      labels: ["testing"],
    },
  ],

  "api-integration": [
    {
      title: "Research third-party APIs",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: [],
    },
    {
      title: "Create API integration service",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["api"],
    },
    {
      title: "Implement webhook receiver",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["api", "feature"],
    },
    {
      title: "Add API authentication",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["api"],
    },
    {
      title: "Create webhook event handlers",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["feature"],
    },
    {
      title: "Implement API rate limiting",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["api", "enhancement"],
    },
    {
      title: "Add API error handling",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["enhancement"],
    },
    {
      title: "Create API integration tests",
      status: "done",
      priority: "medium",
      hasDueDate: false,
      labels: ["testing"],
    },
    {
      title: "Implement webhook security",
      status: "done",
      priority: "high",
      hasDueDate: false,
      labels: ["api"],
    },
    {
      title: "Add API documentation",
      status: "done",
      priority: "low",
      hasDueDate: false,
      labels: ["documentation"],
    },
  ],
};
